export const leads = [
  {
    title: 'Broker Admin',
    company: 'Farlong Holdings - LLC',
    channel: 'Retail',
    created: '3/15/2019',
    status: 'New',
    name: 'George Smith',
    state: 'CA',
    city: 'Irvine',
    loanAmt: 455980,
    phone: '555555555',
    email: 'george@smith.com',
    address: '762 Palantine Rd',
    loanType: '1 year',
    condition: '2',
    milestone: 'XXX',
    linked: 'N/A',
    loanNumber: '153838',
    servicing: 'TBD',
    type: 'Org',
    units: 7,
    volume: '$6,425,000',
    active: true,
    alertType: 'Call Back',
  },
  {
    title: 'Broker Admin',
    company: 'Farlong Holdings - LLC',
    channel: 'Wholesale',
    created: '3/14/2019',
    status: 'In Progress',
    name: 'Walter White',
    state: 'OR',
    city: 'Irvine',
    loanAmt: 324456,
    phone: '555555555',
    email: 'walter@white.com',
    address: '223 Main St',
    loanType: '3 year',
    condition: '4',
    milestone: 'XXX',
    linked: 'N/A',
    loanNumber: '643322',
    servicing: 'TBD',
    type: 'Org',
    units: 7,
    volume: '$2,325,000',
    active: true,
    alertType: 'Followup',
  },
  {
    title: 'Loan Officer',
    company: 'Farlong Holdings - LLC',
    channel: 'Retail',
    created: '3/13/2019',
    status: 'Cold',
    name: 'Ashley Windston',
    state: 'AZ',
    city: 'Irvine',
    loanAmt: 324456,
    phone: '555555555',
    email: 'ashley@windston.com',
    address: '40 Smith West St ',
    loanType: '5 year',
    condition: '3',
    milestone: 'XXX',
    linked: 'N/A',
    loanNumber: '628534',
    servicing: 'TBD',
    type: 'Org',
    units: 7,
    volume: '$625,000',
    active: false,
    alertType: 'New Lead',
  },
  {
    title: 'Loan Officer',
    company: 'Farlong Holdings - LLC',
    channel: 'Wholesale',
    created: '3/12/2019',
    status: 'DNQ',
    name: 'Robert Mendez',
    state: 'AZ',
    city: 'Irvine',
    loanAmt: 324456,
    phone: '555555555',
    email: 'robert@mendez.com',
    address: '45 Autopia',
    loanType: '6 year',
    condition: '4',
    milestone: 'XXX',
    linked: 'N/A',
    loanNumber: '983553',
    servicing: 'TBD',
    type: 'Org',
    units: 7,
    volume: '$22,625,000',
    active: true,
    alertType: 'Call Back',
  },
];
